services:
  mongo:
    image: mongo:8
    ports: ["27017:27017"]
    volumes: [mongo_data:/data/db]
    environment:
      MONGO_INITDB_DATABASE: packattackgg

  redis:
    image: redis:7.4-alpine
    ports: ["6379:6379"]

  maildev:
    image: maildev/maildev:2.2.1
    ports:
      - "1080:1080"
      - "1025:1025"

volumes:
  mongo_data:
